# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitMe
  pod 'Down'

  target 'GitMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitMeUITests' do
    # Pods for testing
  end

end
